services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - webapp
  webapp:
    build: ./webapp
    # ports:
    #   - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
